In [2]:
import numpy as np

## DataTypes & Attributes

In [3]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 3.0, 4.4],
              [5, 6, 6.5 ]])
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [6, 7, 8]],
               [[9, 10, 11],
               [12, 13, 14],
               [15, 16, 17]]])

In [6]:
a2

array([[1. , 3. , 4.4],
       [5. , 6. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
# dimensions of the 3 arrays
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  3.0  4.4
1  5.0  6.0  6.5

## 2. Creating arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones([2, 3])
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros([2, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[4, 9, 6, 2, 3],
       [4, 1, 4, 4, 8],
       [0, 5, 3, 1, 7]])

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.36901085, 0.98848718, 0.39965046],
       [0.34390322, 0.04998444, 0.8683486 ],
       [0.97384924, 0.55898212, 0.66690042],
       [0.1456842 , 0.4822485 , 0.70830236],
       [0.83205603, 0.17658742, 0.83013188]])

In [27]:
random_array_2.shape

(5, 3)

In [28]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.70263178, 0.82967107, 0.15748155],
       [0.79915783, 0.29772068, 0.25985685],
       [0.70405437, 0.94932074, 0.32653268],
       [0.92611871, 0.44848708, 0.18679728],
       [0.78763794, 0.14160127, 0.60248919]])

In [29]:
# Pseudo Random Numbers. The seed predetermine the random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [30]:
random_array_4.shape

(5, 3)

In [31]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [32]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [33]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a1

array([1, 2, 3])

In [35]:
a2

array([[1. , 3. , 4.4],
       [5. , 6. , 6.5]])

In [36]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [37]:
a1[0]

1

In [38]:
a2.shape

(2, 3)

In [39]:
a2[0]

array([1. , 3. , 4.4])

In [40]:
a3.shape

(2, 3, 3)

In [41]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [43]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 9, 10],
        [12, 13]]])

In [44]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4
# 5=the number in the first row
# 4 is the number of rows
# 3 is the set of rows 
# 2 y the number of sets

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [45]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [46]:
# Get the first 4 numbers of the inner most array
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4. Manipulating & comparing arrays

## Arithmetic

In [47]:
a1

array([1, 2, 3])

In [48]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [49]:
a1 + ones

array([2., 3., 4.])

In [50]:
a1 - ones

array([0., 1., 2.])

In [51]:
a1 * ones

array([1., 2., 3.])

In [52]:
a2

array([[1. , 3. , 4.4],
       [5. , 6. , 6.5]])

In [53]:
a1 + a2

array([[2. , 5. , 7.4],
       [6. , 8. , 9.5]])

In [54]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [58]:
# How can you reshape a2 to be compatible with a3?
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [59]:
a1 / ones

array([1., 2., 3.])

In [60]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [5., 3., 2.]])

In [61]:
a2 ** 2

array([[ 1.  ,  9.  , 19.36],
       [25.  , 36.  , 42.25]])

In [62]:
# It's called 'modulo' and shows the remainder of the division
a1 % 2

array([1, 0, 1], dtype=int32)

In [63]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [64]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation
Aggregation = performing the same operation on a number of things

In [65]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [66]:
sum(listy_list)

6

In [67]:
sum(a1)

6

In [68]:
np.sum(a1)

6

Use Python's methods (sum()) on Python datatypes and use NumPy's methods on NumPy arrays (np.sum()).

In [69]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [71]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [72]:
%timeit sum(massive_array) #Python's sum()
%timeit np.sum(massive_array) #NumPy's np.sum()

15.5 ms ± 511 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
30.8 µs ± 52.8 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
