In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1, 3.0, 4.4],
              [5, 6, 6.5 ]])
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [6, 7, 8]],
               [[9, 10, 11],
               [12, 13, 14],
               [15, 16, 17]]])

In [8]:
a2

array([[1. , 3. , 4.4],
       [5. , 6. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
# dimensions of the 3 arrays
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  3.0  4.4
1  5.0  6.0  6.5